include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: ubuntu:bionic

cuda:11.0:
  extends:
    - .test
  variables:
    CI_THOROUGH: 'true'
    JULIA_CUDA_VERSION: '11.0'
    JULIA_CUDA_USE_BINARYBUILDER: 'true'
  tags:
    - nvidia
    - latest
    - cuda_11.0

julia:1.3:
  extends:
    - .julia:1.3
    - .test
    - .cuda:11.0
  tags:
    - nvidia

julia:1.4:
  extends:
    - .julia:1.4
    - .test
    - .cuda:11.0
  tags:
    - nvidia

julia:1.5:
  extends:
    - .julia:1.5
    - .test
    - .cuda:11.0
  tags:
    - nvidia

julia:nightly:
  extends:
    - .julia:nightly
    - .test
    - .cuda:11.0
  tags:
    - nvidia
  allow_failure: true

coverage:
    extends:
    - .julia:1.5
    - .coverage
